
services:
  db:
    build:
      context: .
      dockerfile: mysql-custom.Dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
      
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    container_name: wordpress_app
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./app/wp-content:/var/www/html/wp-content
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_app
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ramon  
    networks:
      - wordpress_network
networks:
  wordpress_network:
volumes:
  db_data: